accounts/urls.py
from django.urls import path
from . import views



app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path("signup/", views.SignupAPIView.as_view(), name="signup"),
    path('profile/<int:id>/', views.UserProfileAPIView.as_view(), name='profile'),
    path('follow/<int:user_id>/', views.FollowUnfollowAPIView.as_view(), name='follow_user'),
]

products/urls.py
from django.urls import path
from . import views


app_name = "products"
urlpatterns = [
    path("product_create/", views.ProductCreateAPIView.as_view(), name="product_create"),
    path("product_list/", views.ProductListAPIView.as_view(), name="product_list"),
    path('product_like/<int:product_id>/', views.ProductLikeAPIView.as_view(), name='like_product'),
    path('product_detail/<int:product_id>/', views.ProductDeleteAPIView.as_view(), name='product_detail'),
    path('product_edit/<int:product_id>/', views.ProductEditAPIView.as_view(), name='product_edit'),
    path('product_delete/<int:product_id>/', views.ProductDeleteAPIView.as_view(), name='product_delete'),
]

sp_market/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('products/', include("products.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block styles %} 
    {% endblock styles %} 

    {% block scripts %} 
    {% endblock scripts %}

  </head>
  <body>
    <div class="base-wrapper">
      <header class="header">
        <div class="logo">
          <h1><a href="{% url 'products:product_list' %}" class="page-title">Sparta Market</a></h1>
        </div>
        <nav>
          <ul class="nav-links">
            <li><a href="{% url 'products:product_create' %}">Register Products</a></li>
            <li><a href="{% url 'accounts:profile' user.id %}">User Profile</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </nav>
      </header>

      <main class="main-content">
        {% block main_content %} {% endblock main_content %}
      </main>

      <footer class="footer">
        <div class="footer-content">
          <!-- 왼쪽 텍스트 버튼 -->
          <div class="footer-links">
            <a href="#">About Us</a>
            <a href="#">Contact</a>
            <a href="#">Terms of Service</a>
            <a href="#">Privacy Policy</a>
          </div>
          <!-- 오른쪽 소셜 아이콘 -->
          <div class="social-icons">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>